SELECT DISTINCT CLIENTE.NOME 
FROM ((CLIENTE INNER JOIN ORDEM_DE_COMPRA ON CLIENTE.CODIGO = ORDEM_DE_COMPRA.CODIGO_CLIENTE) 
INNER JOIN NOTA_FISCAL ON ORDEM_DE_COMPRA.CODIGO_NOTA_FISCAL = NOTA_FISCAL.CODIGO) 
WHERE NOTA_FISCAL.VALOR_TOTAL > 200.00;

SELECT NOTA_FISCAL.CODIGO 
FROM NOTA_FISCAL 
WHERE NOTA_FISCAL.VALOR_TOTAL > 3000 AND NOTA_FISCAL.VALOR_TOTAL < 10000;

SELECT PRODUTO.DESCRICAO, COMPRA_AVALIA_PRODUTO.NOTA 
FROM ((PRODUTO INNER JOIN COMPRA_AVALIA_PRODUTO ON PRODUTO.CODIGO = COMPRA_AVALIA_PRODUTO.CODIGO_PRODUTO) 
INNER JOIN ORDEM_DE_COMPRA ON COMPRA_AVALIA_PRODUTO.CODIGO_COMPRA = ORDEM_DE_COMPRA.CODIGO) 
WHERE PRODUTO.PRECO < ORDEM_DE_COMPRA.VALOR_FRETE;

SELECT COUNT(PRODUTO.NOME) 
FROM ((PRODUTO INNER JOIN COMPRA_POSSUI_PRODUTO ON PRODUTO.CODIGO = COMPRA_POSSUI_PRODUTO.CODIGO_PRODUTO) 
INNER JOIN ORDEM_DE_COMPRA ON COMPRA_POSSUI_PRODUTO.CODIGO_COMPRA = ORDEM_DE_COMPRA.CODIGO) 
WHERE PRODUTO.NOME = 'Caixa de Som' AND ORDEM_DE_COMPRA.DESCONTO = ((PRODUTO.PRECO*45)/100) AND ORDEM_DE_COMPRA.DATA_COMPRA LIKE '%-FEB-2020';

SELECT PRODUTO.NOME, CUPOM_DE_DESCONTO.CODIGO, CUPOM_DE_DESCONTO.DESCONTO 
FROM ((PRODUTO INNER JOIN CUPOM_RESTRICAO_CATEGORIA ON PRODUTO.CODIGO_CATEGORIA = CUPOM_RESTRICAO_CATEGORIA.CODIGO_CATEGORIA) 
INNER JOIN CUPOM_DE_DESCONTO ON CUPOM_DE_DESCONTO.CODIGO = CUPOM_RESTRICAO_CATEGORIA.CODIGO_CUPOM) 
ORDER BY CUPOM_DE_DESCONTO.DESCONTO DESC, PRODUTO.NOME ASC;

SELECT PRODUTO.NOME, PRODUTO.DESCRICAO 
FROM (PRODUTO INNER JOIN PROD_ESTOCADO_CENT_DIST ON PRODUTO.CODIGO = PROD_ESTOCADO_CENT_DIST.CODIGO_PRODUTO) 
WHERE PROD_ESTOCADO_CENT_DIST.QUANTIDADE > 100;

SELECT CLIENTE.NOME 
FROM ((((FORNECEDOR INNER JOIN FORNECEDOR_FORNECE_PRODUTO ON FORNECEDOR.CODIGO = FORNECEDOR_FORNECE_PRODUTO.CODIGO_FORNECEDOR) 
INNER JOIN COMPRA_POSSUI_PRODUTO ON COMPRA_POSSUI_PRODUTO.CODIGO_PRODUTO = FORNECEDOR_FORNECE_PRODUTO.CODIGO_PRODUTO) 
INNER JOIN ORDEM_DE_COMPRA ON ORDEM_DE_COMPRA.CODIGO = COMPRA_POSSUI_PRODUTO.CODIGO_COMPRA) 
INNER JOIN CLIENTE ON CLIENTE.CODIGO = ORDEM_DE_COMPRA.CODIGO_CLIENTE) 
WHERE FORNECEDOR.NOME = 'Berlim Importações LTDA'; 

SELECT AVG(PRODUTO.PRECO) 
FROM PRODUTO INNER JOIN CATEGORIA ON CATEGORIA.CODIGO = PRODUTO.CODIGO_CATEGORIA 
WHERE CATEGORIA.NOME = 'Queijos';

SELECT TRANSPORTADORA.NOME 
FROM (((PRODUTO INNER JOIN COMPRA_POSSUI_PRODUTO ON PRODUTO.CODIGO = COMPRA_POSSUI_PRODUTO.CODIGO_PRODUTO) 
INNER JOIN ORDEM_DE_COMPRA ON ORDEM_DE_COMPRA.CODIGO = COMPRA_POSSUI_PRODUTO.CODIGO_COMPRA) 
INNER JOIN TRANSPORTADORA ON TRANSPORTADORA.CODIGO = ORDEM_DE_COMPRA.CODIGO_TRANSPORTADORA) 
WHERE PRODUTO.NOME != '	Fogão 7 Bocas';

